# Generated by Django 6.0.6 on 2026-07-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='No Subject', max_length=200),
        ),
    ]
