# Generated by Django 6.0.6 on 2026-07-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_contact_subject_remove_contact_submitted_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Contactm',
        ),
    ]
