# Generated by Django 6.0.6 on 2026-07-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_contact_contactm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactm',
            new_name='contact',
        ),
    ]
